### PR TITLE
adds citation and manafest files

### PR DESCRIPTION
**Pull request by alan-stokes**
adds citation and manifest files. start point for further work on creating a doi for the tools

### CODE REVIEW

**Comment by dkfellows** [comment]
Should credit @oliverrhodes, @rjames91 and @ej159 as they all have contributions pending.

**Comment by alan-stokes** [comment]
who is ej159? i have no mapping from github account to person. I know rjames and oliver. but not ej159

**Comment by ej159** [comment]
> who is ej159? i have no mapping from github account to person. I know rjames and oliver. but not ej159

Edward Jones, MSc student

**Comment by alan-stokes** [comment]
hi Edward Jones. Can you send me the following data. 

  orcid: email: website: 

thanks

**Comment by alan-stokes** [comment]
done for edward jones. still missing robert james orcid.

**Comment by alan-stokes** [comment]
im sorry, but i dont know how to fix this one. it keeps trying to find spynnaker8 version 1.4.0.1 when the requirements.txt has already been updated to look for 1.4.0.0 so no idea how to bypass this

**Pull request closed without merging**
