### PR TITLE
Reduce overhead

### PR DESCRIPTION
**Pull request by rowleya**
Fix a couple of the examples for SpiNNakerManchester/sPyNNaker#1195

### CODE REVIEW

**Review by andrewgait — APPROVED** [review]
This looks fine too, though interesting that balanced_random doesn't behave as well now?  Is the same true for the balanced_random example in IntroLab?

**Comment by rowleya** [comment]
I think it is something to do with the live part, though I note that the introlab version does seed things almost identically to what I have done here, so it might just be a coincidence that I hit upon tricky cases on occasion (or the Alan switch was left on ;).

**Review by Christian-B — CHANGES_REQUESTED** [review]
Why the random seeds in the examples/

If only these values work we need an issue.

If any values work now that debugging is finished these should be removed.

**Comment by rowleya** [comment]
We often seed the examples; there are several that have seeds.  However I will remove these and test again...

**Pull request merged**
