### PR TITLE
Parallel examples

### PR DESCRIPTION
**Pull request by rowleya**
Fix issues with ports to let the tests run in parallel.

Tested by SpiNNakerManchester/sPyNNaker8#372, which also runs the tests in parallel (so that needs to be merged too).

### CODE REVIEW

**Comment by Christian-B** [comment]
Not sure how this gets around the port already in use issue as there is still a hard coded port just moved to another place.

I am uncomfortable confirming the rest of the changes due to my lack of experience with the whole external devices stack.

**Comment by rowleya** [comment]
In all testing, the port will not used any fixed values (most have been made None).  It is possible to get a fixed port still in one of the scripts, but this is only when the C visualiser is in use (which it isn't in the tests of course).  In normal cases, the port is read from the connection itself, which should allocate it dynamically (because I set it to None).

**Comment by alan-stokes** [comment]
looks fine to me.

**Comment by rowleya** [comment]
OK, merging this and the PR that updates tests in that case...

**Pull request merged**
