### PR TITLE
Flake8 fixes

### PR DESCRIPTION
**Pull request by dkfellows**
Makes this code pass flake8. I don't know whether we should do this like this, or whether we should just exclude the three files I've changed from flake8 checking…

### CODE REVIEW

**Comment by rowleya** [comment]
I don't really recognise these files.  Is it possible that they have been added by accident?

**Comment by dkfellows** [comment]
Looks like they were added by Simon

**Comment by rowleya** [comment]
Is it clear that they came through a pull request, or is this an accidental commit (or set of commits)?

**Comment by dkfellows** [comment]
Excellent question. Looks like they came in on one commit direct to `master`: 6ac9a400b984daffb0d9a79ad440366d686b4181

**Comment by dkfellows** [comment]
And I've made that commit be on a branch (`get-weight-test`). That branch can also go when this one is merged

**Comment by Christian-B** [comment]
This Pr how has conflicts with master.

**Comment by rowleya** [comment]
As these files are no longer in master, I will close this.

**Pull request closed without merging**
