### PR TITLE
cleaned vogals

### PR DESCRIPTION
**Pull request by alan-stokes**
this no no longer runs without errors. but for some reason is still not determinstic

### CODE REVIEW

**Review by rowleya — APPROVED** [review]
This looks fine.  As a reference for the future, it isn't necessary to introduce a class in an example like this that is only going to run once.  A class is not needed for constants and functions to exist; especially one with no properties!

**Comment by andrewgait** [comment]
It looks fine to me too, though if we can work out why it isn't behaving deterministically when seeded that would be good.

One minor thing: it should be "Vogels", not "Vogals" (there's a mixture of both in the script at the moment).

**Comment by alan-stokes** [comment]
fixed the rename oops. 

may try to look at why the random number generator isnt being used correctly today. depends on what other prs look fun.

**Comment by alan-stokes** [comment]
so to keep whomever reads this updated. 

it seems vogals is not deterministic due to operations on packets arriving too late to be processed in a timer tick. work is ongoing to try to rectify this and hopefully that would make vogals determinstic.

**Pull request closed without merging**
